import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { CallController } from '../src/lib/call-controller';
import { openCallSignal, sealCallSignal } from '../src/lib/call-crypto';
import { CALL_CAPABILITY, type CallEnvelope, type CallIceConfiguration } from '../src/lib/call-types';
import { generateIdentity } from '../src/lib/crypto';
import { authenticatedMlsCallMembers } from '../src/lib/call-membership';
import { createCreatorMlsState, prepareCreatorWelcome, joinMlsGroup, prepareMlsMembership, processMlsMembership } from '../src/lib/mls';
import type { Vault } from '../src/lib/types';

import { getUserMedia, Track, Stream, Peer, pair, setup, invite, deferred, SDP } from './helpers/call-harness';
describe('foreground call controller security lifecycle', () => {
  it('fails closed when an adapter returns raw ICE config without local identity verification', async () => {
    const { a } = await pair();
    const { controller, getIceConfig, sent } = setup(a);
    getIceConfig.mockImplementation(async () => ({ iceServers: [], iceTransportPolicy: 'all', relayConfigured: false }));
    await controller.start('audio');
    expect(Peer.instances).toHaveLength(0);
    expect(getUserMedia).not.toHaveBeenCalled();
    expect(sent).toHaveLength(0);
    expect(controller.state.statusText).toContain('对方未准备好安全通话');
  });
  it('does not emit an offer or request capture for an unattested substituted encryption key', async () => {
    const { a, b } = await pair();
    const attacker = await generateIdentity();
    const substituted = { ...a, members: a.members.map((member) => member.deviceId === b.identity.publicBundle.deviceId ? { ...member, encryptionKey: attacker.publicBundle.encryptionKey } : member) };
    // The MLS leaf binds the signing key; an independent signed identity proof is required for this ECDH metadata.
    await authenticatedMlsCallMembers(substituted);
    const { controller, getIceConfig, sent } = setup(substituted);
    getIceConfig.mockImplementation(async () => ({ iceServers: [], iceTransportPolicy: 'all', relayConfigured: false, verifiedPeerIds: [] }));
    await controller.start('video');
    expect(Peer.instances).toHaveLength(0);
    expect(getUserMedia).not.toHaveBeenCalled();
    expect(sent).toHaveLength(0);
    expect(controller.state.statusText).toContain('对方未准备好安全通话');
  });
  it('sends invitations only to devices in the locally verified identity-proof list', async () => {
    const { a, b } = await pair();
    const extraIdentity = await generateIdentity();
    const extra = { ...extraIdentity.publicBundle, role: 'joiner' as const, status: 'active' as const, joinProof: null, addedBy: b.identity.publicBundle.deviceId, capabilities: [CALL_CAPABILITY] };
    const added = await prepareMlsMembership(b, 'add', extra);
    const vault: Vault = { ...a, members: [...a.members, extra], mls: { ...a.mls! } };
    vault.mls!.groupState = await processMlsMembership(vault, added.event, 1);
    vault.mls!.lastEventSeq = 1;
    await authenticatedMlsCallMembers(vault);
    const { controller, getIceConfig, sent } = setup(vault);
    getIceConfig.mockImplementation(async () => ({ iceServers: [], iceTransportPolicy: 'all', relayConfigured: false, verifiedPeerIds: [b.identity.publicBundle.deviceId] }));
    await controller.start('audio');
    expect(sent.map((envelope) => envelope.recipientId)).toEqual([b.identity.publicBundle.deviceId]);
  });
  it('requires the caller identity proof before accepting and capturing media', async () => {
    const { a, b } = await pair();
    const { controller, getIceConfig, sent } = setup(b);
    getIceConfig.mockImplementation(async () => ({ iceServers: [], iceTransportPolicy: 'all', relayConfigured: false, verifiedPeerIds: [] }));
    await controller.receive(await invite(a, b));
    await controller.accept();
    expect(Peer.instances).toHaveLength(0);
    expect(getUserMedia).not.toHaveBeenCalled();
    expect(sent).toHaveLength(0);
    expect(controller.state.statusText).toContain('对方未准备好安全通话');
  });
  it('verifies an incoming invitation before showing it and never requests media before acceptance', async () => {
    const { a, b } = await pair();
    const { controller, sent } = setup(b);
    const envelope = await invite(a, b);
    await controller.receive({ ...envelope, callId: crypto.randomUUID() });
    expect(controller.state.phase).toBe('idle');
    await controller.receive(envelope);
    expect(controller.state.phase).toBe('incoming');
    expect(getUserMedia).not.toHaveBeenCalled();
    expect(Peer.instances).toHaveLength(0);
    await controller.accept();
    expect(getUserMedia).toHaveBeenCalledOnce();
    expect(sent[0]?.action).toBe('accept');
    expect(sent.slice(1).every((item) => item.action === 'signal')).toBe(true);
    expect((await openCallSignal(a, sent[0]!)).description?.type).toBe('answer');
  });
  it('processes a queued signed cancellation even when its invite is still decrypting', async () => {
    const { a, b } = await pair();
    const { controller } = setup(b);
    const envelope = await invite(a, b);
    const canceled = await sealCallSignal(a, b.identity.publicBundle.deviceId, envelope.callId, 'end', { kind: 'video', reason: 'canceled' });
    await Promise.all([controller.receive(envelope), controller.receive(canceled)]);
    expect(controller.state.phase).toBe('ended');
    expect(getUserMedia).not.toHaveBeenCalled();
  });
  it('does not resurrect an invitation after a terminal server state arrived during decryption', async () => {
    const { a, b } = await pair();
    const { controller } = setup(b);
    const envelope = await invite(a, b);
    const receiving = controller.receive(envelope);
    controller.serverEvent({ type: 'call-state', callId: envelope.callId, state: 'ended', code: 'CALL_ENDED' });
    await receiving;
    expect(controller.state.phase).toBe('idle');
    const sibling = setup(b);
    const next = await invite(a, b);
    const nextReceiving = sibling.controller.receive(next);
    sibling.controller.serverEvent({ type: 'call-state', callId: next.callId, state: 'accepted', acceptedBy: crypto.randomUUID() });
    await nextReceiving;
    expect(sibling.controller.state.phase).toBe('idle');
    expect(getUserMedia).not.toHaveBeenCalled();
  });
  it('prevents replayed invites from ringing again after the call is dismissed', async () => {
    const { a, b } = await pair();
    const { controller } = setup(b);
    const envelope = await invite(a, b);
    await controller.receive(envelope);
    await controller.decline();
    controller.dismiss();
    await controller.receive(envelope);
    expect(controller.state.phase).toBe('idle');
    expect(getUserMedia).not.toHaveBeenCalled();
  });
  it('immediately closes the peer and stops a late permission grant after privacy lock', async () => {
    const { a } = await pair();
    const { controller, session, sent, onPermissionChange } = setup(a);
    const permission = deferred<Stream>();
    getUserMedia.mockReturnValue(permission.promise);
    const starting = controller.start('video');
    await vi.waitFor(() => expect(getUserMedia).toHaveBeenCalledOnce());
    const peer = Peer.instances[0]!;
    controller.destroy();
    session.vault = null;
    expect(peer.close).toHaveBeenCalledOnce();
    expect(onPermissionChange.mock.calls.map(([active]) => active)).toEqual([true, false]);
    const granted = new Stream([new Track('audio'), new Track('video')]);
    permission.resolve(granted);
    await starting;
    await Promise.resolve();
    expect(granted.getTracks().every((track) => track.stop.mock.calls.length > 0)).toBe(true);
    expect(sent).toHaveLength(0);
  });
  it('invalidates a late ICE configuration response and never starts capture after hangup', async () => {
    const { a } = await pair();
    const { controller, getIceConfig } = setup(a);
    const config = deferred<{ iceServers: never[]; iceTransportPolicy: 'all'; relayConfigured: false }>();
    getIceConfig.mockReturnValue(config.promise);
    const starting = controller.start('audio');
    await controller.hangup();
    config.resolve({ iceServers: [], iceTransportPolicy: 'all', relayConfigured: false });
    await starting;
    expect(getUserMedia).not.toHaveBeenCalled();
    expect(Peer.instances).toHaveLength(0);
  });
  it('sends no caller ICE to ringing siblings and stops capture synchronously when hung up', async () => {
    const { a } = await pair();
    const { controller, sent } = setup(a);
    await controller.start('video');
    expect(sent.map((envelope) => envelope.action)).toEqual(['invite']);
    const stream = controller.state.localStream as unknown as Stream;
    const ending = controller.hangup();
    expect(stream.getTracks().every((track) => track.stop.mock.calls.length > 0)).toBe(true);
    expect(Peer.instances[0]!.close).toHaveBeenCalledOnce();
    await ending;
    expect(sent.at(-1)?.action).toBe('end');
  });
  it('honors first-device acceptance and tears down the losing callee without ending the winner', async () => {
    const { a, b } = await pair();
    const { controller, sent } = setup(b);
    const envelope = await invite(a, b);
    await controller.receive(envelope);
    const permission = deferred<Stream>();
    getUserMedia.mockReturnValue(permission.promise);
    const accepting = controller.accept();
    await vi.waitFor(() => expect(getUserMedia).toHaveBeenCalledOnce());
    controller.serverEvent({ type: 'call-state', callId: envelope.callId, state: 'accepted', acceptedBy: crypto.randomUUID() });
    expect(controller.state.statusText).toContain('其他设备');
    const granted = new Stream([new Track('audio'), new Track('video')]);
    permission.resolve(granted);
    await accepting;
    expect(granted.getTracks().every((track) => track.stop.mock.calls.length > 0)).toBe(true);
    expect(sent).toHaveLength(0);
  });
  it('rejects late answers and stops an established call when the peer is revoked', async () => {
    const { a, b } = await pair();
    const { controller, session, sent } = setup(a);
    await controller.start('audio');
    const callId = sent[0]!.callId;
    const answer = await sealCallSignal(b, a.identity.publicBundle.deviceId, callId, 'accept', { kind: 'audio', description: { type: 'answer', sdp: SDP } });
    await controller.receive(answer);
    const peer = Peer.instances[0]!;
    expect(peer.setRemoteDescription).toHaveBeenCalledOnce();
    session.vault = { ...a, members: a.members.map((member) => member.deviceId === b.identity.publicBundle.deviceId ? { ...member, status: 'revoked' } : member) };
    controller.updateMembers();
    expect(controller.active).toBe(false);
    expect(peer.close).toHaveBeenCalledOnce();
    await controller.receive(await sealCallSignal(b, a.identity.publicBundle.deviceId, callId, 'accept', { kind: 'audio', description: { type: 'answer', sdp: SDP } }));
    expect(peer.setRemoteDescription).toHaveBeenCalledOnce();
  });
  it('stops video capture when camera is off and upgrades audio without renegotiation', async () => {
    const { a, b } = await pair();
    const { controller, sent } = setup(a);
    await controller.start('audio');
    await controller.receive(await sealCallSignal(b, a.identity.publicBundle.deviceId, sent[0]!.callId, 'accept', { kind: 'audio', description: { type: 'answer', sdp: SDP } }));
    const peer = Peer.instances[0]!;
    expect(peer.transceivers.map((item) => item.receiver.track.kind)).toEqual(['audio', 'video']);
    await controller.toggleCamera();
    expect(controller.state.cameraEnabled).toBe(true);
    const video = (controller.state.localStream as unknown as Stream).getVideoTracks()[0]!;
    await controller.toggleCamera();
    expect(video.stop).toHaveBeenCalledOnce();
    expect(controller.state.cameraEnabled).toBe(false);
    expect(peer.createOffer).toHaveBeenCalledOnce();
    const media = await openCallSignal(b, sent.at(-1)!);
    expect(media.cameraEnabled).toBe(false);
    controller.toggleMicrophone();
    expect(controller.state.micMuted).toBe(true);
    expect(controller.state.localStream!.getAudioTracks()[0]!.enabled).toBe(false);
  });
  it('keeps ringing other devices after one recipient is unavailable and ends on a deliberate decline', async () => {
    const { a, b } = await pair();
    const extraIdentity = await generateIdentity();
    const extra = { ...extraIdentity.publicBundle, role: 'joiner' as const, status: 'active' as const, joinProof: null, addedBy: b.identity.publicBundle.deviceId, capabilities: [CALL_CAPABILITY] };
    const added = await prepareMlsMembership(b, 'add', extra);
    const vault: Vault = { ...a, members: [...a.members, extra], mls: { ...a.mls! } };
    vault.mls!.groupState = await processMlsMembership(vault, added.event, 1);
    vault.mls!.lastEventSeq = 1;
    await authenticatedMlsCallMembers(vault);
    const { controller, sent } = setup(vault);
    await controller.start('audio');
    const callId = sent[0]!.callId;
    controller.serverEvent({ type: 'call-state', callId, state: 'error', code: 'CALL_UNAVAILABLE', recipientId: extra.deviceId });
    expect(controller.state.phase).toBe('outgoing');
    const declined = await sealCallSignal(b, a.identity.publicBundle.deviceId, callId, 'decline', { kind: 'audio', reason: 'declined' });
    await controller.receive(declined);
    expect(controller.active).toBe(false);
    expect(controller.state.statusText).toContain('拒绝');
    const next = setup(vault);
    await next.controller.start('audio');
    const nextCallId = next.sent[0]!.callId;
    next.controller.serverEvent({ type: 'call-state', callId: nextCallId, state: 'error', code: 'CALL_UNAVAILABLE', recipientId: extra.deviceId });
    next.controller.serverEvent({ type: 'call-state', callId: nextCallId, state: 'error', code: 'CALL_UNAVAILABLE', recipientId: b.identity.publicBundle.deviceId });
    expect(next.controller.active).toBe(false);
    expect(next.controller.state.statusText).toContain('不在线');
  });
  it('ignores a late sibling-invite rejection after the server selected a device', async () => {
    const { a, b } = await pair();
    const { controller, sent } = setup(a);
    await controller.start('audio');
    const callId = sent[0]!.callId;
    controller.serverEvent({ type: 'call-state', callId, state: 'accepted', acceptedBy: b.identity.publicBundle.deviceId });
    controller.serverEvent({ type: 'call-state', callId, state: 'error', code: 'CALL_ALREADY_ACCEPTED', recipientId: crypto.randomUUID() });
    expect(controller.active).toBe(true);
  });
  it('refreshes ICE credentials on the scheduled renewal and cancels future renewal on teardown', async () => {
    const { a, b } = await pair();
    const { controller, sent, getIceConfig } = setup(a);
    await controller.start('audio');
    await controller.receive(await sealCallSignal(b, a.identity.publicBundle.deviceId, sent[0]!.callId, 'accept', { kind: 'audio', description: { type: 'answer', sdp: SDP } }));
    const peer = Peer.instances[0]!;
    vi.useFakeTimers();
    controller.state.remoteStream!.addTrack(new Track('audio') as unknown as MediaStreamTrack);
    peer.iceConnectionState = 'connected';
    peer.connectionState = 'connected';
    peer.onconnectionstatechange?.();
    await vi.advanceTimersByTimeAsync(60 * 60_000);
    expect(getIceConfig).toHaveBeenCalledTimes(2);
    expect(peer.setConfiguration).toHaveBeenCalledOnce();
    expect(peer.createOffer).toHaveBeenCalledTimes(1);
    controller.destroy();
    await vi.advanceTimersByTimeAsync(2 * 60 * 60_000);
    expect(getIceConfig).toHaveBeenCalledTimes(2);
  });
  it('bounds ringing to 45 seconds and ignores an expired replay', async () => {
    const { a, b } = await pair();
    const envelope = await invite(a, b);
    vi.useFakeTimers();
    const { controller } = setup(b);
    await controller.receive(envelope);
    await vi.advanceTimersByTimeAsync(45_001);
    expect(controller.state.phase).toBe('ended');
    expect(controller.state.statusText).toBe('未接听');
    controller.dismiss();
    await controller.receive(envelope);
    expect(controller.state.phase).toBe('idle');
  });
});
