import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium, webkit } from 'playwright';
import { createServer } from 'vite';

const server = await createServer({ configFile: false, appType: 'custom', root: process.cwd(), logLevel: 'error', server: { host: '127.0.0.1', port: 0, hmr: false } });
server.middlewares.use('/__desktop', (_req, res) => { res.setHeader('Content-Type','text/html'); res.end('<!doctype html><html><meta name="viewport" content="width=device-width,initial-scale=1"><body><div id="app"></div></body></html>'); });
let browser;
const screenshots = path.join(tmpdir(), 'quiet-room-desktop-qa');
await mkdir(screenshots, { recursive: true });
try {
  await server.listen();
  for (const engine of [chromium, webkit]) {
    browser = await engine.launch(engine === chromium && !process.env.CI ? process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : { channel: 'chrome' } : {});
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
    page.setDefaultTimeout(12000);
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://localhost:${server.httpServer.address().port}/__desktop`);
    await page.evaluate(async () => {
      for (const name of ['styles','chat-layout','gallery','auth-recovery','chat-interactions','cover','voice-messages','call','motion','desktop']) await import(`/src/${name}.css`);
      const { QuietRoomApp } = await import('/src/app.ts');
      const vault = await import('/src/lib/vault.ts');
      const spaces = await import('/src/lib/spaces.ts');
      const app = new QuietRoomApp(document.querySelector('#app'));
      const own = { deviceId: crypto.randomUUID(), role: 'creator', status: 'active' }, peer = { deviceId: crypto.randomUUID(), role: 'joiner', status: 'active' };
      const session = await vault.createVault({ v: 1, roomId: crypto.randomUUID(), accessToken: 'desktop-fixture', role: 'creator', protocol: 'legacy-v1', lastSeq: 80, members: [own, peer], identity: { publicBundle: own } }, 'desktop-fixture-password', 'password');
      await spaces.rememberLocalSpace(session, undefined, { roomId: session.vault.roomId, name: '两个人的日常' });
      app.session = session; app.privacyCovered = false; app.runtimeAbort = new AbortController(); app.uiPreferencesHydrated = true;
      app.uiPreferences = { recoveryReminderDismissed: true, entranceCardDismissed: true };
      app.updateSafetyCode = async () => {}; app.updateBackgroundNotificationControl = async () => {}; app.showReleaseNotesIfNeeded = () => {};
      app.unreadCounter.markRead = async () => {};
      Object.defineProperty(document, 'hasFocus', { configurable: true, value: () => true });
      app.messages = new Map(Array.from({ length: 80 }, (_, i) => {
        const seq = i + 1, time = '2026-09-28T12:00:00Z';
        return [seq, { seq, clientMsgId: `desktop-message-${seq}`, senderId: i % 2 ? own.deviceId : peer.deviceId, payload: { v: 1, kind: 'text', text: `${seq} 今天一起去看展览吧。` + (i % 5 === 0 ? '这是用于验证宽度变化和阅读位置的长消息。'.repeat(12) : ''), sentAt: time }, acceptedAt: time, status: 'delivered' }];
      }));
      app.renderChat(); app.renderMessages({ scroll: 'bottom' });
      window.fixture = { app, session, spaces };
    });
    await page.locator('.desktop-sidebar .space-row').waitFor();
    const settle = async () => { await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))); await page.waitForFunction(() => !window.fixture.app.chatViewportMotion?.moving && !window.fixture.app.composerHeightMotion); };
    await settle();
    const dimensions = () => page.evaluate(() => {
      const rect = selector => { const r = [...document.querySelectorAll(selector)].at(-1).getBoundingClientRect(); return { x:r.x, y:r.y, right:r.right, bottom:r.bottom, width:r.width, height:r.height }; };
      return { shell:rect('.chat-shell'), input:rect('#composer'), row:rect('.composer-row'), list:rect('#message-list'), incoming:rect('.message.incoming'), outgoing:rect('.message.outgoing'), rootScroll:scrollY, overflow:document.documentElement.scrollWidth > innerWidth };
    });
    const assertComposerSurface = async () => {
      const surface = await page.locator('#composer').evaluate(el => ({ background:getComputedStyle(el).backgroundColor,
        controls:[...el.querySelectorAll('.composer-input-stack,.icon-button')].map(control=>getComputedStyle(control).backgroundColor) }));
      assert.ok(surface.controls.every(color=>color===surface.background), `P1 continuous composer surface: ${JSON.stringify(surface)}`);
    };
    let geometry = await dimensions();
    await assertComposerSurface();
    assert.equal(geometry.shell.x, 280, JSON.stringify(geometry));
    assert.equal(geometry.rootScroll, 0);
    assert.ok(!geometry.overflow && geometry.input.bottom <= 900, JSON.stringify(geometry));
    assert.ok(Math.abs(geometry.incoming.x - geometry.shell.x - 28) < 2 && Math.abs(geometry.outgoing.right - geometry.shell.right + 28) < 2, JSON.stringify(geometry));
    assert.equal(await page.locator('.message-text').last().evaluate(el => el.dispatchEvent(new Event('selectstart', { bubbles: true, cancelable: true }))), true, 'Desktop permits direct text selection');
    await page.locator('#message-input').fill('第一行草稿\n第二行草稿\n第三行草稿');
    await settle();
    await page.evaluate(() => { window.inputIdentity = document.querySelector('#message-input'); const list = document.querySelector('#message-list'); list.dispatchEvent(new WheelEvent('wheel',{deltaY:-500,bubbles:true})); list.scrollTop -= 700; });
    await page.waitForTimeout(100);
    const anchor = await page.evaluate(() => window.fixture.app.captureChatAnchor());
    await page.locator('.desktop-sidebar .space-close').click();
    await settle();
    assert.equal(await page.locator('#message-input').evaluate(el => el === window.inputIdentity), true);
    assert.equal(await page.locator('#message-input').inputValue(), '第一行草稿\n第二行草稿\n第三行草稿');
    assert.equal(await page.locator('.desktop-sidebar').isVisible(), false);
    geometry = await dimensions(); assert.equal(geometry.shell.x, 0);
    const after = await page.evaluate(() => window.fixture.app.captureChatAnchor());
    assert.equal(after.clientMsgId, anchor.clientMsgId); assert.ok(Math.abs(after.offset - anchor.offset) <= 2, JSON.stringify({ anchor, after }));
    await page.locator('#open-chat-tools').press('Enter');
    await assertComposerSurface();
    assert.equal(await page.locator('#chat-tools button:not(:disabled)').first().evaluate(el => el === document.activeElement), true);
    const toolGeometry = await page.evaluate(() => {
      const tools = document.querySelector('#chat-tools').getBoundingClientRect(), row = document.querySelector('.composer-row').getBoundingClientRect(), plus = document.querySelector('#open-chat-tools').getBoundingClientRect();
      return { left:tools.left - plus.left, gap:row.top - tools.bottom, right:tools.right, top:tools.top };
    });
    assert.ok(Math.abs(toolGeometry.left) <= 1 && Math.abs(toolGeometry.gap - 8) <= 1 && toolGeometry.top >= 0 && toolGeometry.right <= 1440, JSON.stringify(toolGeometry));
    await page.keyboard.press('Escape'); assert.equal(await page.locator('#open-chat-tools').getAttribute('aria-expanded'), 'false');
    await page.locator('#open-spaces').click();
    await page.screenshot({ path: `${screenshots}/${engine.name()}-chat.png` });
    await page.locator('#space-settings').click();
    await page.locator('.desktop-settings-page #presence-style-setting').waitFor();
    assert.equal(await page.locator('.desktop-sidebar').isVisible(), true);
    await page.locator('.desktop-sidebar .space-close').click();
    assert.equal(await page.locator('.desktop-settings-page .desktop-sidebar-toggle').count(), 1);
    await page.locator('.desktop-settings-page .desktop-sidebar-toggle').click();
    await page.locator('.desktop-settings-page #release-history').click();
    await page.locator('#release-history-back').click();
    await page.locator('.desktop-settings-page #presence-style-setting').waitFor();
    await page.locator('.desktop-settings-page .space-back').click();
    await page.locator('#message-input').waitFor(); await settle();
    assert.ok((await page.locator('#message-input').boundingBox()).height > 60, 'Multiline draft height must survive returning');
    for (const size of [{width:1920,height:1080},{width:1024,height:600},{width:1366,height:420},{width:800,height:600},{width:390,height:680},{width:1440,height:900}]) {
      const beforeResize = await page.evaluate(() => fixture.app.captureChatAnchor());
      await page.setViewportSize(size); await settle();
      await assertComposerSurface();
      const afterResize = await page.evaluate(() => fixture.app.captureChatAnchor());
      assert.equal(afterResize?.clientMsgId, beforeResize?.clientMsgId, JSON.stringify({size,beforeResize,afterResize}));
      if (!beforeResize?.pinnedToBottom) assert.ok(Math.abs(afterResize.offset-beforeResize.offset)<=2, JSON.stringify({size,beforeResize,afterResize}));
      const bounds = await page.locator('#composer').boundingBox();
      assert.ok(bounds.y >= 0 && bounds.y + bounds.height <= size.height + 2, JSON.stringify({size,bounds}));
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
      assert.equal(await page.locator('#message-input').inputValue(), '第一行草稿\n第二行草稿\n第三行草稿');
    }
    await page.locator('#open-chat-tools').click(); await page.locator('#open-favorites').click();
    await page.locator('.gallery-header .desktop-sidebar-toggle').waitFor();
    await page.locator('#gallery-tab-files').click();
    assert.equal(await page.locator('.gallery-header .desktop-sidebar-toggle').count(), 1, 'Category rerender retains desktop navigation');
    const gallery = await page.locator('.gallery-header').boundingBox();
    assert.ok(gallery.x >= 280 && gallery.x + gallery.width <= 1441, JSON.stringify(gallery));
    await page.screenshot({path:`${screenshots}/${engine.name()}-favorites.png`});
    await page.locator('#gallery-back').click(); await settle();
    await page.locator('.desktop-sidebar .space-close').click();
    await page.setViewportSize({width:800,height:600}); await settle();
    await page.setViewportSize({width:1440,height:900}); await settle();
    assert.equal(await page.locator('.desktop-sidebar').isVisible(), false, 'Desktop collapse choice survives narrow window');
    await page.locator('#open-spaces').click();
    // A sidebar modal must not turn visible background rows into read receipts.
    await page.locator('.desktop-sidebar .space-row').press('F2');
    await page.locator('#space-rename').click();
    await page.evaluate(() => { fixture.reads = 0; fixture.app.unreadCounter.markRead = async () => { fixture.reads++; }; fixture.app.markVisibleMessagesRead(); });
    assert.equal(await page.evaluate(() => fixture.reads), 0);
    await page.locator('#space-name-cancel').click();
    await page.setViewportSize({width:800,height:600}); await settle();
    await page.locator('#open-spaces').click();
    await page.locator('.space-drawer-overlay.is-visible').waitFor();
    await page.locator('.space-drawer-overlay .space-close').focus();
    for (let i=0;i<12;i++) await page.keyboard.press('Shift+Tab');
    assert.equal(await page.evaluate(() => Boolean(document.activeElement.closest('.space-drawer-overlay'))), true, await page.evaluate(() => JSON.stringify({active:document.activeElement.outerHTML.slice(0,350),drawer:document.querySelector('.space-drawer-overlay')?.outerHTML.slice(0,350),rootInert:document.querySelector('#app').inert})));
    await page.keyboard.press('Escape');
    await page.locator('.space-drawer-overlay').waitFor({ state:'detached' });
    await page.setViewportSize({width:1366,height:420}); await settle();
    await page.locator('#open-chat-tools').click();
    const panel = await page.locator('#chat-tools').boundingBox(); assert.ok(panel.y >= 80 && panel.y + panel.height <= 420, JSON.stringify(panel));
    await page.screenshot({path:`${screenshots}/${engine.name()}-short.png`});
    await page.evaluate(() => window.fixture.app.closeChatTools());
    await page.emulateMedia({colorScheme:'dark'});
    await page.setViewportSize({width:1440,height:900});
    await page.screenshot({path:`${screenshots}/${engine.name()}-dark.png`});
    await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pagehide')));
    assert.equal(await page.locator('.desktop-sidebar').count(), 0, 'Privacy teardown must remove space names and previews');
    assert.equal(await page.locator('.message').count(), 0);
    await page.evaluate(() => {
      const {app} = fixture; app.privacyCovered = false; app.session = null; app.browserAccessAbort = new AbortController();
      app.browserProfile = {profile: {spaces: [{roomId:crypto.randomUUID(),name:'尚未授权的空间'}], pending:{}}};
      document.documentElement.classList.remove('privacy-obscured'); document.body.className = 'app-mode';
      app.renderBrowserShell();
    });
    await page.locator('.desktop-sidebar .space-row').waitFor();
    assert.equal(await page.locator('#message-input,.message').count(), 0, 'Directory recognition does not open chat or history');
    const restricted = await page.locator('.browser-access-shell').boundingBox(); assert.equal(restricted.x, 280);
    await page.evaluate(() => fixture.app.cleanupRuntime());
    assert.deepEqual(errors, []);
    await browser.close(); browser = null;
    console.log(`PASS desktop layout ${engine.name()}: alignment, collapse, anchor, keyboard, settings, responsive, privacy`);
  }
} finally { await browser?.close(); await server.close(); }
