import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';
import { createServer } from 'vite';
const server = await createServer({ configFile: false, appType: 'custom', root: process.cwd(), logLevel: 'error', server: { host: '127.0.0.1', port: 0, hmr: false } });
server.middlewares.use('/__read', (_req, res) => { res.setHeader('Content-Type', 'text/html'); res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><main id="app"></main>'); });
let browser;
try {
  await server.listen();
  browser = process.env.QUIET_ROOM_TEST_BROWSER === 'webkit' ? await webkit.launch() : await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : process.env.CI ? {} : { channel: 'chrome' });
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`http://localhost:${server.httpServer.address().port}/__read`);
  const result = await page.evaluate(async () => {
    for (const style of ['styles', 'chat-layout', 'chat-interactions', 'cover']) await import(`/src/${style}.css`);
    const { QuietRoomApp } = await import('/src/app.ts');
    const { createVault, loadOutbox, saveHistoryMessage, loadMessageEventHistory } = await import('/src/lib/vault.ts');
    const app = new QuietRoomApp(document.querySelector('#app'));
    const own = { deviceId: crypto.randomUUID(), role: 'creator', status: 'active', capabilities: ['message-read-v1', 'media-read-v1'] };
    const peer = { ...own, deviceId: crypto.randomUUID(), role: 'joiner' };
    const session = await createVault({ v: 1, roomId: crypto.randomUUID(), accessToken: 'read-fixture', role: 'creator', protocol: 'legacy-v1', lastSeq: 0, members: [own, peer], identity: { publicBundle: own } }, 'read-fixture-password', 'password');
    app.session = session; app.privacyCovered = false; app.runtimeAbort = new AbortController();
    app.uiPreferencesHydrated = true; app.uiPreferences = { recoveryReminderDismissed: true };
    let cursorWrites = 0;
    app.updateSafetyCode = async () => {}; app.attemptSend = async () => {}; app.unreadCounter.markRead = async () => { cursorWrites++; };
    let focused = false;
    Object.defineProperty(document, 'hasFocus', { configurable: true, value: () => focused });
    const time = new Date().toISOString();
    const record = (seq, senderId, text) => ({ seq, senderId, clientMsgId: crypto.randomUUID(), status: 'delivered', acceptedAt: time, payload: { v: 1, kind: 'text', text, sentAt: time } });
    const outgoing = record(1, own.deviceId, 'Delivered is not read');
    app.messages.set(1, outgoing); app.renderChat(); app.renderMessages({ scroll: 'bottom' });
    const row = document.querySelector(`[data-client-msg-id="${outgoing.clientMsgId}"]`);
    const bubble = row.querySelector('.message-bubble');
    const check = (condition, reason) => { if (!condition) throw Error(reason); };
    check(row.querySelectorAll('.message-delivery path').length === 1, 'Delivery was incorrectly presented as read');
    const read = { ...record(2, peer.deviceId, ''), payload: { v: 1, kind: 'message-read', sentAt: time, target: { serverSeq: 1, clientMsgId: outgoing.clientMsgId, senderId: own.deviceId } } };
    app.messages.set(2, read); app.renderMessages();
    check(row.querySelectorAll('.message-delivery path').length === 2 && row.querySelector('.message-delivery').dataset.state === 'read', 'Read receipt did not add the second arm');
    check(bubble === row.querySelector('.message-bubble'), 'Read receipt replaced bubble content');
    check(document.querySelectorAll('article.message').length === 1, 'Read event leaked into timeline');
    await saveHistoryMessage(session, outgoing); await saveHistoryMessage(session, read);
    const events = await loadMessageEventHistory(session);
    check(events.some(event => event.payload.kind === 'message-read'), 'Read receipt was lost on history reload');
    app.messages.delete(2); app.messageEventHistory = new Map(events.map(event => [event.seq, event])); app.renderMessages();
    check(row.querySelectorAll('.message-delivery path').length === 2, 'Paged-out read receipt was lost');
    const incoming = record(3, peer.deviceId, 'Visible text'); app.messages.set(3, incoming); app.renderMessages({ scroll: 'bottom' });
    await new Promise(resolve => setTimeout(resolve, 450));
    app.markVisibleMessagesRead();
    check((await loadOutbox(session)).length === 0, 'Unfocused page emitted a read receipt');
    check(cursorWrites === 0, 'Unfocused page incorrectly cleared the cover unread count');
    focused = true; app.setActiveSurface('away'); app.markVisibleMessagesRead();
    check((await loadOutbox(session)).length === 0, 'Away surface emitted a read receipt');
    app.setActiveSurface('chat'); peer.capabilities = []; app.markVisibleMessagesRead();
    check((await loadOutbox(session)).length === 0, 'Unsupported peer received a new payload kind');
    peer.capabilities = ['message-read-v1', 'media-read-v1'];
    const companion = { ...own, deviceId: crypto.randomUUID(), capabilities: [] };
    session.vault.members.push(companion); app.markVisibleMessagesRead();
    check((await loadOutbox(session)).length === 0, 'An outdated third device did not fence the incompatible encrypted event');
    check(app.deviceCard(companion, false).textContent.includes('已读同步待更新'), 'Blocking companion was not identified in device management');
    companion.capabilities = ['message-read-v1', 'media-read-v1'];
    app.markVisibleMessagesRead(); app.markVisibleMessagesRead();
    for (let n = 0; n < 100 && !(await loadOutbox(session)).length; n++) await new Promise(resolve => setTimeout(resolve, 20));
    const queued = await loadOutbox(session);
    check(queued.length === 1 && queued[0].payload.kind === 'message-read' && queued[0].payload.target.clientMsgId === incoming.clientMsgId, 'Visible message must persist exactly one encrypted read event');
    app.cleanupRuntime();
    return { sentArms: 1, readArms: 2, persistedRead: true, replayDeduplicated: true, focusSurfaceAndCapabilityGates: true };
  });
  assert.deepEqual(errors, []); console.log('Message read:', result);
} finally { await browser?.close(); await server.close(); }
